# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 22:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkm_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookmarks',
            new_name='Bookmark',
        ),
    ]
