# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkm_app', '0002_auto_20170220_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='date_added',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='bkm_descrip',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='bkm_name',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='bkm_owner',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='bkm_url',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
